### ISSUE TITLE
Doesn't build with Node 5.3

### ISSUE THREAD

**Issue by ThatRendle** [samgiles/node-libuuid#1]
I appreciate this project hasn't been updated in a while, but when I try to install it with Node 5.3 bad things happen:

```
> node-libuuid@1.1.0 install /home/mark/ctm/variant-assignment/variant-assignment/node_modules/node-libuuid
> node-gyp rebuild

make: Entering directory '/home/mark/ctm/variant-assignment/variant-assignment/node_modules/node-libuuid/build'
  CXX(target) Release/obj.target/node_libuuid/lib/libuuid.o
../lib/libuuid.cc:7:30: error: ‘Arguments’ does not name a type
 Handle<Value> Generate(const Arguments& args) {
                              ^
In file included from /home/mark/.node-gyp/5.3.0/include/node/node.h:42:0,
                 from ../lib/libuuid.cc:2:
/home/mark/.node-gyp/5.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> Generate(const int&)’:
/home/mark/.node-gyp/5.3.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../lib/libuuid.cc:8:17: error: within this context
     HandleScope scope;
                 ^
../lib/libuuid.cc:13:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(String::New(uuid_string));
                  ^
../lib/libuuid.cc:13:24: error: ‘New’ is not a member of ‘v8::String’
     return scope.Close(String::New(uuid_string));
                        ^
../lib/libuuid.cc: At global scope:
../lib/libuuid.cc:16:34: error: ‘Arguments’ does not name a type
 Handle<Value> GenerateTime(const Arguments& args) {
                                  ^
In file included from /home/mark/.node-gyp/5.3.0/include/node/node.h:42:0,
                 from ../lib/libuuid.cc:2:
/home/mark/.node-gyp/5.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> GenerateTime(const int&)’:
/home/mark/.node-gyp/5.3.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../lib/libuuid.cc:17:14: error: within this context
  HandleScope scope;
              ^
../lib/libuuid.cc:22:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close(String::New(uuid_string));
               ^
../lib/libuuid.cc:22:21: error: ‘New’ is not a member of ‘v8::String’
  return scope.Close(String::New(uuid_string));
                     ^
../lib/libuuid.cc: At global scope:
../lib/libuuid.cc:25:36: error: ‘Arguments’ does not name a type
 Handle<Value> GenerateRandom(const Arguments& args) {
                                    ^
In file included from /home/mark/.node-gyp/5.3.0/include/node/node.h:42:0,
                 from ../lib/libuuid.cc:2:
/home/mark/.node-gyp/5.3.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> GenerateRandom(const int&)’:
/home/mark/.node-gyp/5.3.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../lib/libuuid.cc:26:14: error: within this context
  HandleScope scope;
              ^
../lib/libuuid.cc:31:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close(String::New(uuid_string));
               ^
../lib/libuuid.cc:31:21: error: ‘New’ is not a member of ‘v8::String’
  return scope.Close(String::New(uuid_string));
                     ^
../lib/libuuid.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../lib/libuuid.cc:35:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("generate"), FunctionTemplate::New(Generate)->GetFunction());
                  ^
../lib/libuuid.cc:35:79: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("generate"), FunctionTemplate::New(Generate)->GetFunction());
                                                                               ^
In file included from /home/mark/.node-gyp/5.3.0/include/node/node.h:42:0,
                 from ../lib/libuuid.cc:2:
/home/mark/.node-gyp/5.3.0/include/node/v8.h:4348:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/mark/.node-gyp/5.3.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../lib/libuuid.cc:36:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
  exports->Set(String::NewSymbol("generate_time"), FunctionTemplate::New(Generate)->GetFunction());
               ^
../lib/libuuid.cc:36:81: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
  exports->Set(String::NewSymbol("generate_time"), FunctionTemplate::New(Generate)->GetFunction());
                                                                                 ^
In file included from /home/mark/.node-gyp/5.3.0/include/node/node.h:42:0,
                 from ../lib/libuuid.cc:2:
/home/mark/.node-gyp/5.3.0/include/node/v8.h:4348:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/mark/.node-gyp/5.3.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../lib/libuuid.cc:37:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
  exports->Set(String::NewSymbol("generate_random"), FunctionTemplate::New(GenerateRandom)->GetFunction());
               ^
../lib/libuuid.cc:37:89: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
  exports->Set(String::NewSymbol("generate_random"), FunctionTemplate::New(GenerateRandom)->GetFunction());
                                                                                         ^
In file included from /home/mark/.node-gyp/5.3.0/include/node/node.h:42:0,
                 from ../lib/libuuid.cc:2:
/home/mark/.node-gyp/5.3.0/include/node/v8.h:4348:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/mark/.node-gyp/5.3.0/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
node_libuuid.target.mk:92: recipe for target 'Release/obj.target/node_libuuid/lib/libuuid.o' failed
make: *** [Release/obj.target/node_libuuid/lib/libuuid.o] Error 1
make: Leaving directory '/home/mark/ctm/variant-assignment/variant-assignment/node_modules/node-libuuid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.15-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mark/ctm/variant-assignment/variant-assignment/node_modules/node-libuuid
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm ERR! Linux 4.1.15-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "node-libuuid"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! node-libuuid@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libuuid@1.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libuuid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libuuid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libuuid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mark/ctm/variant-assignment/variant-assignment/npm-debug.log
```

I don't know enough about native Node stuff to fix and PR this :(

**Comment by samgiles** [comment]
Thanks for the report, I think I've just fixed this with a 2.0.0 release.  Please try  with that - I've only got access to a Mac OS X machine right now, but it should be cross platform.
